// Code generated by "stringer -type=MsgType"; DO NOT EDIT.

package vuvuzela

import "fmt"

const _MsgType_name = "MsgConvoRequestMsgBadRequestErrorMsgConvoErrorMsgConvoResponseMsgAnnounceConvoRound"

var _MsgType_index = [...]uint8{0, 15, 33, 46, 62, 83}

func (i MsgType) String() string {
	if i >= MsgType(len(_MsgType_index)-1) {
		return fmt.Sprintf("MsgType(%d)", i)
	}
	return _MsgType_name[_MsgType_index[i]:_MsgType_index[i+1]]
}
