// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package mixnet

import (
	json "encoding/json"
	easyjson "github.com/davidlazar/easyjson"
	jlexer "github.com/davidlazar/easyjson/jlexer"
	jwriter "github.com/davidlazar/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDecodePublicServerConfigCba82e03(in *jlexer.Lexer, out *PublicServerConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Key":
			if in.IsNull() {
				in.Skip()
				out.Key = nil
			} else {
				out.Key = in.BytesReadable()
			}
		case "Address":
			out.Address = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEncodePublicServerConfigCba82e03(out *jwriter.Writer, in PublicServerConfig) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Key\":")
	out.Base32Bytes(in.Key)
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Address\":")
	out.String(string(in.Address))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PublicServerConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEncodePublicServerConfigCba82e03(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PublicServerConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEncodePublicServerConfigCba82e03(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PublicServerConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDecodePublicServerConfigCba82e03(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PublicServerConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDecodePublicServerConfigCba82e03(l, v)
}
